name: Make Installers

on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install NSIS
        run:  sudo apt update && sudo apt install -y nsis nsis-pluginapi
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
      - name: Update config versions
        run: ./update-windows-installer-version.sh 
      - name: Install launch4j prereqs
        run:  sudo apt install -y libncurses5 lib32z1
      - name:  Make executable (launch4j)
        run: sudo chmod +x ./launch4j-linux/launch4j
      - name: Make executable windres
        run: sudo chmod +x ./launch4j-linux/bin/windres
      - name: Make Java executable on Windows (launch4j)
        run: sudo ./launch4j-linux/launch4j launch4j.cfg.xml
      - name: Make debian package
        run:  ./debian/create-deb.sh
      - name: Create NSIS Installer
        uses: joncloud/makensis-action@v3.7
        with:
          script-file: ${{ github.workspace }}/install.nsi
      - name: Upload target/origami-smtp.jar
        uses: actions/upload-artifact@v3
        with:
          path: target/origami-smtp.jar
