name: Make Installers

on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install NSIS
        run:  sudo apt update && sudo apt install -y nsis nsis-pluginapi
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
      - name: Create NSIS Installer
        uses: joncloud/makensis-action@v3.7
        with:
          additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins
