name: Make Installers

on: [push]

jobs:
  release:
    name: Release to Github Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./
          asset_name: origami-smtp_v2.0.0-setup.exe
          asset_content_type: application/octet-stream

  build:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install NSIS
        run:  sudo apt update && sudo apt install -y nsis nsis-pluginapi
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
      - name: Update config versions
        run: ./update-windows-installer-version.sh 
      - name: Install launch4j prereqs
        run:  sudo apt install -y libncurses5 lib32z1
      - name:  Make executable (launch4j)
        run: sudo chmod +x ./launch4j-linux/launch4j
      - name: Make executable windres
        run: sudo chmod +x ./launch4j-linux/bin/windres
      - name: Make Java executable on Windows (launch4j)
        run: sudo ./launch4j-linux/launch4j launch4j.cfg.xml
      - name: Make debian package
        run:  ./debian/create-deb.sh
      - name: Create NSIS Installer
        uses: joncloud/makensis-action@v3.7
        with:
          script-file: ${{ github.workspace }}/install.nsi
      - name: Make jar file without version
        run: cp target/OrigamiGUI-*.jar target/origami-smtp.jar
      - name: Upload target/origami-smtp.jar
        uses: actions/upload-artifact@v3
        with:
          path: target/origami-smtp.jar
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          path: origami-smtp_*.exe
      - name: Upload Debian Insaller
        uses: actions/upload-artifact@v3
        with:
          path: origami-smtp_*.deb
