name: Make Windows Installer

on: [push]

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: jdk+fx
      - name: Download NSIS
        run:  Invoke-Webrequest -URI http://gigenet.dl.sourceforge.net/project/nsis/NSIS%202/2.51/nsis-2.51.zip -OutFile nsis.zip
      - name: Unzip NSIS
        run:  Expand-Archive nsis.zip
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
      - name: Update Installer Versions [Powershell Script]
        run:  update-installer-version.ps1